### ISSUE TITLE
DRYing up your code through chained selectors

### ISSUE THREAD

**Issue by abb1991** [gui365/prj-rev-bwfs-tea-cozy#2]
You have an opportunity to DRY (Don't Repeat Yourself) up your code, by finding classes that share similar styling, and chaining them together.

For example

```
.class-1 {
  color: blue;
}

.class-2 {
  color: blue;
}

.class-3 {
  color: blue;
}

```

becomes:

```
.class-1, 
.class-2, 
.class-3 {
  color: blue;
}
```

I'd suggest looking through your code and seeing if you can find any common classes that can be chained together.

**Comment by gui365** [comment]
Will do. Thank you.
